### ISSUE TITLE
When I down your model ,but model is not !  did u upload wrong

### ISSUE THREAD

**Issue by anthonyyuan** [arthur-qiu/StyleFaceV#1]
pretrained_models
├── network-snapshot-005000.pkl  # styleGAN3 checkpoint finetuned on both RAVDNESS and unaligned FFHQ.
├── wing.ckpt                    # Face Alignment model from https://github.com/protossw512/AdaptiveWingLoss.
├── motion_net.pth               # trained motion sampler.
├── pre_net.pth
└── pre_pose_net.pth
checkpoints/stylefacev
├── latest_net_FE.pth            # appearance extractor + recompostion 
├── latest_net_FE_lm.pth         # first half of pose extractor
└── latest_net_FE_pose.pth       # second half of pose extractor

**Comment by arthur-qiu** [comment]
Thanks for pointing out it. I fix the link.

**Comment by arthur-qiu** [comment]
I think this problem is solved.
