### ISSUE TITLE
There aren't rnn_dnet3, rnn_dnet

### ISSUE THREAD

**Issue by rlgnswk** [arthur-qiu/StyleFaceV#3]
Hi, Thank you for great work.

I am curious about the architector of your models but there aren't rnn_dnet3, rnn_dnet in "models" folder 

are they miss-uploaded things, or are you guys plan to upload later?

**Comment by arthur-qiu** [comment]
Hi, thanks for pointing out this problem. I have uploaded them and please pull the whole project again.

**Comment by rlgnswk** [comment]
I checked it!
Thanks for your rapid reply!!
