### ISSUE TITLE
Question about quantitive studies

### ISSUE THREAD

**Issue by hallwaypzh** [arthur-qiu/StyleFaceV#4]
Thanks for you awesome work; however i am curious:
1. Number of video samples to compute FVD.
2. The train-test split of RAVDESS dataset (Since StyleFaceV needs an initial frame).
3. Will you guys release retrained Di-GAN, StyleGAN-V, MC-HD?

**Comment by arthur-qiu** [comment]
Hi, 
  1, 2048.
  2, Initial frame can be sampled from the noise directly.
  3, No. We retrain them by their default setting and it is easy to reproduce.
