### ISSUE TITLE
Pre stage using new datasets

### ISSUE THREAD

**Issue by jerrymatjila** [arthur-qiu/StyleFaceV#5]
Your work shows stunning results.

When using new datasets can please elaborate on how to prepare data that goes to `dataroot2` 
https://github.com/arthur-qiu/StyleFaceV/blob/b8619d4ad82726f32140cd0e8c9f4f976644ebc3/models/stylepose_model.py#L76

**Comment by arthur-qiu** [comment]
It is the dataset of unaligned FFHQ. Please refer to "Reproducing the unaligned FFHQ" at https://github.com/NVlabs/ffhq-dataset. We set random-shift to 0.1 because we find that 0.2 will make the face out of the window.

**Comment by jerrymatjila** [comment]
Thank you.
