### ISSUE TITLE
network-snapshot-005000.pkl

### ISSUE THREAD

**Issue by why128** [arthur-qiu/StyleFaceV#6]
network-snapshot-005000.pkl  这个模型能在发下下载地址吗

**Comment by why128** [comment]
https://catalog.ngc.nvidia.com/orgs/nvidia/teams/research/models/stylegan3/files  这个模型适用吗

**Comment by arthur-qiu** [comment]
> https://catalog.ngc.nvidia.com/orgs/nvidia/teams/research/models/stylegan3/files 这个模型适用吗

这个链接里的模型是在纯图像数据集上训练的，我们基于此在视频数据调优了，调优后的模型本来就发布在pretrain model部分里的google drive，详情请参照readme部分
